//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectProgressMonitoringSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public string Marks { get; set; }
        public string ProjectID { get; set; }
        public string PhaseID { get; set; }
        public string TeacherID { get; set; }
        public string StudentUSN { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual Project Project { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
